from typing import Dict, List

__version__: str

class Inflector:
    def __init__(self, artifact_path: str, overlay_path: str = ...) -> None: ...
    def decline(self, word: str, number: str, case: str) -> List[str]: ...
    def paradigm(self, word: str) -> Dict[str, Dict[str, List[str]]]: ...
